// src/app/components/projects/Project.tsx
import Image, { StaticImageData } from "next/image";
import Link from "next/link";
import { Card } from "..";

export function Project({
    name,
    image,
    description,
    links,
    tags,
}: PageProps) {
    return (
        <Card>
            <div className="lg:flex lg:justify-between px-5 py-2 border-background border-b-8">
                <h1 className="my-auto text-2xl lg:text-4xl w-full lg:text-left">
                    {name}
                </h1>
                <h1 className="flex flex-row gap-2 justify-center">
                    {createTags(tags)}
                </h1>
            </div>
            <div className="flex-col justify-between">
                <Image
                    className="p-5 mx-auto"
                    src={image}
                    alt={`${name} image`}
                    style={{
                        width: "50%",
                        height: "auto",
                        minWidth: "350px",
                    }}
                ></Image>
                <div className="flex justify-center gap-5">
                    {links?.map(({ href, alt, text, logo }) =>
                        <Link
                            href={href}
                            className="flex border-black bg-white text-black  w-28 md:w-36 text-xl md:p-2 rounded lg justify-around"
                            target="_blank"
                            key={href}
                        >
                            <Image
                                src={logo}
                                style={{
                                    width: "35px",
                                    height: "auto",
                                }}
                                alt={alt}
                            />
                            <p className="my-auto">{text}</p>
                        </Link>
                    )}
                </div>

                <p className="py-5 sm:text-xl lg:text-2xl w-3/4 mx-auto text-sm">
                    {description}
                </p>
            </div>
        </Card>
    );
}

type PageProps = {
    description: string;
    image: StaticImageData;
    links?: Link[];
    name: string;
    tags: string[];
}

export type Link = { href: string, logo: StaticImageData, text: string, alt: string };

function createTags(tags: string[]) {
    return tags.map((tag) => (
        <span
            key={tag}
            className="border lg:border-2 rounded-lg p-1 lg:p-2 text-sm lg:text-xl"
        >
            {tag}
        </span>
    ));
}

// src/lib/components/Project.svelte
<script lang="ts">
	export let name: string;
	export let src: string;
	export let description: string;
	export let links: { href: string; text: string; logo: string }[];
	export let tags: string[] = [];
</script>

<div id="container">
	<h2>{name}</h2>
	<div class="tags">
		{#each tags as tag}
			<p class="tag">{tag}</p>
		{/each}
	</div>
	<img {src} alt={`${name} image`} />
	<div id="links">
		{#each links as link}
			<a class="text-700" href={link.href} target="_blank">
				<img class="logo" src={link.logo} alt={`${link.text} logo`} />
				<p class="linkText">
					{link.text}
				</p>
			</a>
		{/each}
	</div>
	<p id="description" class="text-500">{description}</p>
</div>

<style>
	#container {
		display: flex;
		flex-direction: column;
		border-radius: 1.5rem;
		background-color: var(--secondary-background);
	}

	#links {
		padding: 1rem 0 0 0;
		display: flex;
		justify-content: center;
		gap: 1rem;
	}

	.linkText {
		margin: 0;
		line-height: 1.5;
	}

	a {
    color: var(--primary-background);
		text-decoration: none;
		display: flex;
		gap: 0.3rem;
		align-content: center;
	}

	h2 {
		text-align: center;
		font-size: 1.8rem;
    margin-bottom: 0;
	}

	#description {
		font-size: 1.2rem;
		padding: 0 2rem 1rem 2rem;
	}

	.logo {
		width: 25px;
		height: 25px;
	}

	.tag {
		border: solid var(--primary-background) 4px;
    border-radius: 5px;
    padding: 0.3rem;
    font-size: clamp(8px, 1vw, 1rem);
    font-weight: 700;
	}
   .tags {
    color: var(--primary-background);
    padding: 0.5rem 0 0.5rem 0;
    margin: 0;
    display: flex;
    justify-content: center;
    gap: 0.5rem;

  }

  .tags p {
    margin: 0;
  }
</style>
